<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Rag.Core\Rag.Core.csproj" />
    <ProjectReference Include="..\..\src\Rag.Application\Rag.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime.Managed" />
    <PackageReference Include="Tokenizers.DotNet" />
    <PackageReference Include="Tokenizers.DotNet.runtime.win-x64" />
  </ItemGroup>

</Project>
